version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
    networks:
      - tree-calculator-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - tree-calculator-network

networks:
  tree-calculator-network:
    driver: bridge

volumes:
  uploads:
  results:
